# Generated by Django 6.0.3 on 2026-06-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracao', models.IntegerField()),
                ('descricao', models.CharField(max_length=200)),
                ('modalidade', models.CharField(max_length=50)),
            ],
        ),
    ]
